version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2

executors:
  ruby27:
    docker:
      - image: circleci/ruby:2.7-node-browsers

jobs:
  humid:
    parameters:
      ruby-version:
        type: executor
      gemfile:
        type: string
    executor: << parameters.ruby-version >>
    steps:
      - checkout
      - run:
          name: Using Gemfile
          command: mv -f ./<< parameters.gemfile >> ./Gemfile
      - run:
          name: Bundle install
          working_directory: ./breezy_rails
          command: bundle install
      - run:
          name: Rspec
          working_directory: ./breezy_rails
          command: bundle exec rspec

workflows:
  tests:
    jobs:
      - humid:
          matrix:
            parameters:
              gemfile:
                - Gemfile.webpacker54
                - Gemfile.webpacker43
              ruby-version:
                - ruby27
